//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_voting_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Advertisement
    {
        public long National_ID { get; set; }
        public string Name { get; set; }
        public string list_Or_party_name { get; set; }
        public int Circle_ID { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
        public string Status { get; set; }
    }
}
