//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_voting_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectionSchedule
    {
        public int ID { get; set; }
        public Nullable<System.DateTime> Start_Date_Of_Nominate { get; set; }
        public Nullable<System.TimeSpan> Start_Hour_Of_Nominate { get; set; }
        public Nullable<System.DateTime> End_Date_Of_Nominate { get; set; }
        public Nullable<System.TimeSpan> End_Hour_Of_Nominate { get; set; }
        public Nullable<System.DateTime> Start_Date_Of_Election { get; set; }
        public Nullable<System.TimeSpan> Start_Hour_Of_Election { get; set; }
        public Nullable<System.DateTime> End_Date_Of_Election { get; set; }
        public Nullable<System.TimeSpan> End_Hour_Of_Election { get; set; }
    }
}
