//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_voting_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ElectionAdvertisement
    {
        public int ID { get; set; }
        public long National_ID { get; set; }
        public string List_Name { get; set; }
        public string Party_Name { get; set; }
        public string Circle { get; set; }
        public string Name { get; set; }
        public Nullable<int> Circle_ID { get; set; }
        public string Description { get; set; }
        public string URL { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<int> PaymentID { get; set; }
        public string Plan { get; set; }
        public Nullable<int> LikeCount { get; set; }
    
        public virtual PayPalPayment PayPalPayment { get; set; }
    }
}
