//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_voting_System.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class local_Candidates_Request
    {
        public int Circle_ID { get; set; }
        public string List_Name { get; set; }
        public string Email { get; set; }
        public string Name { get; set; }
        public long National_ID { get; set; }
        public string Gender { get; set; }
        public System.DateTime Birth_Date { get; set; }
        public string Type_of_Chair { get; set; }
        public string Religion { get; set; }
        public string Status { get; set; }
    }
}
