//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace E_voting_System.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    //public partial class localCandidate
    //{
    //    public int CandidateId { get; set; }

    //    public string Name { get; set; }
    //    [Required(ErrorMessage = "الرقم الوطني مطلوب ")]
    //    [StringLength(100, MinimumLength = 10, ErrorMessage = "الرقم الوطني يجب ان يكون 10 ارقام")]
    //    public string National_ID { get; set; }
    //    [Required(ErrorMessage = "اسم المرشح مطلوب")]
    //    public string Candidate_Name { get; set; }
    //    [Required(ErrorMessage = "مسار الترشح مطلوب")]
    //    public string Type_Of_Chair { get; set; }
    //    [Required(ErrorMessage = "اسم القائمة مطلوب")]
    //    public string List_Name { get; set; }
    //    public Nullable<int> Counter { get; set; }
    //    public string Picture { get; set; }
    //    public Nullable<int> List_ID { get; set; }
    //}
    public partial class localCandidate
    {
        public int CandidateId { get; set; }

        [Required(ErrorMessage = "الرقم الوطني مطلوب ")]
         public string National_ID { get; set; }

        [Required(ErrorMessage = "اسم المرشح مطلوب")]
        public string Candidate_Name { get; set; }

        [Required(ErrorMessage = "مسار الترشح مطلوب")]
        public string Type_Of_Chair { get; set; }
        
        public string List_Name { get; set; }
        public Nullable<int> Counter { get; set; }
        public string Picture { get; set; }
        public Nullable<int> List_ID { get; set; }
    }
}
