//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;

namespace E_voting_System.Models
{
    using System;
    using System.Collections.Generic;

    public partial class PartyList
    {
        public int ID { get; set; }
        [Required(ErrorMessage = "اسم الحزب مطلوب")]

        public string Party_Name { get; set; }
        [Required(ErrorMessage = "اسم القائمة مطلوب")]

        public string List_Name { get; set; }
        [Required(ErrorMessage = "الرقم الوطني للمفوض مطلوب")]
        public int Delegate_ID { get; set; }
        [Required(ErrorMessage = "اسم المفوض مطلوب")]
        public string Delegate_Name { get; set; }
        [Required(ErrorMessage = "رقم الهاتف للمفوض مطلوب")]
        [Phone(ErrorMessage = "رقم الهاتف غير صحيح")]
        public string Delegate_Phone { get; set; }
        [Required(ErrorMessage = "البريد الالكتروني مطلوب")]
        [EmailAddress(ErrorMessage = "البريد الالكتروني غير صالح")]
        public string Delegate_Email { get; set; }
        public int Counter { get; set; }
        public string Status { get; set; }
        public string reason { get; set; }
        public string List_Logo { get; set; }
    }
}